const state = () => ({
    all: [
        {
            id: 1,
            type:'Свитер',
            name: 'Linen crochet trim t-shirt',
            price: 191.00,
            offer: true,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: false,
            image:'https://images.wbstatic.net/big/new/15620000/15629401-1.jpg',
            imageHover: require('../assets/img/img-hover1.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 2,
            name: 'Neck empire sleeve t-shirts',
            price: 300.00,
            type:'Свитер',
            offer: false,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: false,
            image: 'https://aliradar.com/api/image?url=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FH19190e5488a748f59262c2e585502357E%2F-.jpg_480x480.jpg_Q80.jpg_.webp',
            imageHover: require('../assets/img/img-hover2.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 3,
            name: 'Mermaid pencil midi lace',
            price: 166.00,
            type:'Свитер',
            offer: true,
            offerPrice: 5,
            latest: true,
            bestSellers: false,
            trending: false,
            image: 'https://aliradar.com/api/image?url=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FH19190e5488a748f59262c2e585502357E%2F-.jpg_480x480.jpg_Q80.jpg_.webp',
            imageHover: require('../assets/img/img-hover3.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 4,
            name: 'Criss-cross V neck bodycon',
            price: 200.00,
            offer: false,
            type:'Свитер',
            offerPrice: 7,
            latest: true,
            bestSellers: false,
            trending: false,
            image: 'https://aliradar.com/api/image?url=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FH19190e5488a748f59262c2e585502357E%2F-.jpg_480x480.jpg_Q80.jpg_.webp',
            imageHover: require('../assets/img/img-hover4.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 5,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            type:'Свитер',
            latest: true,
            bestSellers: false,
            trending: false,
            image: 'https://www.wantedshop.ru/upload/iblock/efc/efcd988c2c2d0f52bb3c5fd86c7aa88e.jpg',
            imageHover: require('../assets/img/img-hover5.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 6,
            name: 'Tenku remastered',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            latest: true,
            type:'Обувь',
            bestSellers: false,
            trending: false,
            image: 'https://fashion-ua.com.ua/img/uploads/5808/%D0%91%D0%B5%D0%B7-%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8-1.jpg',
            imageHover: require('../assets/img/img-hover6.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 7,
            name: 'Women\'s sherpa lined hoodie',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            type:'Обувь',
            latest: true,
            bestSellers: false,
            trending: false,
            image: 'https://wantedshop.ru/upload/resize_cache/iblock/e22/800_1200_1/e22297a77b41d2d6c08232476b76479c.jpg',
            imageHover: require('../assets/img/img-hover7.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 8,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            type:'Обувь',
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            image: 'https://images.shafastatic.net/214040676',
            imageHover: require('../assets/img/img-hover8.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 9,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            type:'Мойка',
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/bestseller-img1.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img1.jpg'),
            timePeriod: true,
            dateTime: new Date("August 19, 2022 17:00:00 PDT")
        },
        {
            id: 10,
            name: 'Tenku remastered',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            type:'Мойка',
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/bestseller-img2.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img2.jpg'),
            timePeriod: false,
            trendingProducts: false,
            dateTime: new Date("August 19, 2021 17:00:00 PDT")
        },
        {
            id: 11,
            name: 'Women\'s sherpa lined hoodie',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            type:'Мойка',
            latest: false,
            bestSellers: true,
            type:'Свитер',
            trending: false,
            image: 'https://aliradar.com/api/image?url=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FH19190e5488a748f59262c2e585502357E%2F-.jpg_480x480.jpg_Q80.jpg_.webp',
            imageHover: require('../assets/img/bestseller-hover-img3.jpg'),
            timePeriod: true,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 12,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            type:'Мойка',
            offerPrice: 4,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/bestseller-img4.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img4.jpg'),
            timePeriod: false,
            dateTime: new Date("April 19, 2020 17:00:00 PDT")
        },
        {
            id: 13,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            type:'Мойка',
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/trending-img1.jpg'),
            imageHover: require('../assets/img/trending-hover-img1.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 14,
            name: 'Tenku remastered',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            type:'Мойка',
            trending: true,
            image:'https://images.wbstatic.net/big/new/15620000/15629401-1.jpg',
            imageHover: require('../assets/img/trending-hover-img2.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 15,
            name: 'Women\'s sherpa lined hoodie',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            latest: false,
            type:'Мойка',
            bestSellers: false,
            trending: true,
            image:'https://images.wbstatic.net/big/new/15620000/15629401-1.jpg',
            imageHover: require('../assets/img/trending-hover-img3.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 16,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            type:'Мойка',   
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: true,
            image: 'https://sc01.alicdn.com/kf/HTB1tKbCePnD8KJjSspbq6zbEXXaG/202215330/HTB1tKbCePnD8KJjSspbq6zbEXXaG.jpg_.webp',
            imageHover: require('../assets/img/trending-hover-img4.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
    ]
});

export default {
    state
};